MAP*: handle the "alist of numeric K-Vs" case
This fixes a bug that was appearing when you tried:

    > (load-module 'srfi-19)
    Error: car: not a pair: 34

The code from SRFI-19 that was likely causing the failure:

    (define tm:leap-second-table
     '((1230768000 . 34)
      (1136073600 . 33)
      (915148800 . 32)
      (867715200 . 31)
      ...